[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
env_logger = "0.11.8"
async-trait = "0.1.89"
tokio = { version = "1.49.0", features = ["full"] }
pingora = { version = "0.6.0", features = [ "lb", "boringssl" ] }
instant-acme = { version = "0.8.4", features = [ "time", "x509-parser" ] }
hickory-server = { version = "0.25.2" }
